# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled11.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtGui import QIcon


import sys
from PyQt5.QtWidgets import QMainWindow, QApplication, QAction
from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -20, 861, 671))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-size:48pt;\">1488524267gjrjqj</span></p></body></html>"))


class Window(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super(Window, self).__init__()
        self.setupUi(self)
        self.setWindowTitle("Шаблон")

        self.label.setStyleSheet('font: 75 20pt "MS Shell Dlg 2";')

        self.toolbar = QtWidgets.QToolBar(self)
        self.toolbar.setObjectName("toolbar")
        self.addToolBar(QtCore.Qt.TopToolBarArea, self.toolbar)
        self.krug = QtWidgets.QAction(QtGui.QIcon("circle.png"),"",self)
        self.toolbar.addAction(self.krug)
        self.kvadrat = QtWidgets.QAction(QtGui.QIcon("квадрат.png"), "", self)
        self.toolbar.addAction(self.kvadrat)
        self.treugolnik = QtWidgets.QAction(QtGui.QIcon("треугольник.png"), "", self)
        self.toolbar.addAction(self.treugolnik)
        self.treugolnik.triggered.connect(self.s_treugolnik)
        self.kvadrat.triggered.connect(self.s_kvadrat)
        self.krug.triggered.connect(self.s_krug)

    def s_treugolnik(self):
        self.label.setText("S:S = 1/2 · a · h\n"
                           "P:a + b + c")

    def s_kvadrat(self):
        self.label.setText("S:a*a\n"
                           "P:a*4")

    def s_krug(self):
        self.label.setText("S:π × r²\n"
                           "P:d*π = 2*r*π")
   
def application():
    app = QApplication(sys.argv)
    window = Window()
    window.show()
    sys.exit(app.exec())










if __name__ == "__main__":
    application()
